apiVersion: "v2"
name: "config-controller"
description: "Chart holding config-controller."
home: "https://github.com/giantswarm/config-controller"
version: "0.0.1-dev"
appVersion: "0.0.1-dev"
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
annotations:
  application.giantswarm.io/team: "honeybadger"
  config.giantswarm.io/version: 1.x.x
  ui.giantswarm.io/logo: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
restrictions:
  clusterSingleton: true
  fixedNamespace: kube-system
  gpuInstances: false
