image:
  name: "giantswarm/config-controller"
  tag: "[[ .Version ]]"

k8sJwtToVaultTokenImage:
  name: giantswarm/k8s-jwt-to-vault-token
  tag: 0.1.0

pod:
  user:
    id: 1000
  group:
    id: 1000
project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

registry:
  domain: docker.io

managementCluster:
  name: ""

vault:
  address: ""

github:
  token: ""

# Add seccomp to pod security context
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

# Add seccomp to container security context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

serviceMonitor:
  enabled: true
  # -- (duration) Prometheus scrape interval.
  interval: "60s"
  # -- (duration) Prometheus scrape timeout.
  scrapeTimeout: "45s"

podSecurityStandards:
  enforced: false
