apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  config.yaml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      app:
        unique: true
      github:
        repositoryName: {{ .Values.github.repositoryName }}
        repositoryRef: {{ .Values.github.repositoryRef }}
        sharedConfigRepository:
          name: {{ .Values.github.sharedConfigRepository.name }}
          ref: {{ .Values.github.sharedConfigRepository.ref }}
      installation:
        name: {{ .Values.managementCluster.name }}
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
      vault:
        address: {{ .Values.vault.address }}
