apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  secret.yaml: {{ printf "service: {gitHub: {token: %q}}" .Values.Installation.V1.Secret.SilenceOperator.Github.Token | b64enc | quote }}

