apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
stringData:
  secret.yaml: |
    service:
      gitHub:
        ssh:
          key: {{ .Values.github.ssh.key | quote }}
          password: {{ .Values.github.ssh.password | quote }}
        token: {{ .Values.github.token | quote }}
        sharedConfigRepository:
          key: {{ .Values.github.sharedConfigRepository.key | quote }}
          password: {{ .Values.github.sharedConfigRepository.password | quote }}
