apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  annotations:
    giantswarm.io/monitoring-path: "/metrics"
    giantswarm.io/monitoring-port: "8000"
spec:
  ports:
  - name: http
    port: 8000
  selector:
    {{- include "labels.selector" . | nindent 4 }}
