version: 2.1

orbs:
  architect: giantswarm/architect@dev:rm-unique

workflows:
  build:
    jobs:
      - architect/push-to-app-collection:
          name: push-config-controller-to-test-app-collection
          context: architect
          app_name: "config-controller"
          app_namespace: "giantswarm"
          app_collection_repo: "test-app-collection"
          #unique: "true"
          #requires:
          #  - push-config-controller-to-app-catalog
          #filters:
          #  branches:
          #    ignore: /.*/
          #  tags:
          #    only: /^v.*/

