version: 2.1

orbs:
  architect: giantswarm/architect@5.11.1

workflows:
  build:
    jobs:
    - architect/go-build:
        name: go-build
        binary: config-controller
        filters:
          tags:
            only: /^v.*/

    - architect/push-to-registries:
        context: architect
        name: push-to-registries
        requires:
        - go-build
        filters:
          tags:
            only: /^v.*/

          branches:
            ignore:
            - main
            - master
    - architect/push-to-app-catalog:
        context: architect
        name: push-config-controller-to-app-catalog
        app_catalog: control-plane-catalog
        app_catalog_test: control-plane-test-catalog
        chart: config-controller
        requires:
        - push-to-registries
        filters:
          tags:
            only: /^v.*/

          branches:
            ignore:
            - main
            - master
    - architect/push-to-app-collection:
        name: push-config-controller-to-aws-app-collection
        context: architect
        app_name: config-controller
        app_namespace: giantswarm
        app_collection_repo: aws-app-collection
        requires:
        - push-config-controller-to-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        name: push-config-controller-to-azure-app-collection
        context: architect
        app_name: config-controller
        app_namespace: giantswarm
        app_collection_repo: azure-app-collection
        requires:
        - push-config-controller-to-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/
