---
Installation:
  V1:
    Name: ""
    Auth:
      Vault:
        Address: ""
    Secret:
      ConfigController:
        GitHub:
          Token: ""
      SilenceOperator:
        Github:
          Token: ""
